//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dom_texniki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int id { get; set; }
        public Nullable<int> kod { get; set; }
        public string Name_tovar { get; set; }
        public Nullable<double> Sell { get; set; }
    }
}
